name: Build Rule Book

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - ".github/**"
      - "assets/gimp-files/**"
      - "components_lists/**"
      - .gitignore
      - .pre-commit-config.yaml
      - README.md
      - components_list.tex
      - make_printable.sh

jobs:
  build_rule_book:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language:
          - en
          - pl
    steps:
      - name: Set up repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          extra_system_packages: "inkscape"
          root_file: main_${{ matrix.language }}.tex
          latexmk_shell_escape: true
